### ISSUE TITLE
Related stories / pages

### ISSUE THREAD

**Issue by mortendk** [mortendk/saga11#115]
Adding related storties / pages 

config.yml

```yml
      - name: related
        label: Related pages and post
        widget: object
        collapsed: false
        summary: "{{fields.teaser}} / {{fields.image}}"
        fields:
        - name: pages
          label: Related Pages
          widget: relation
          collection: page
          searchFields: [title]
          valueField: "{{url}}"
          displayFields: ["url: {{url}}  - Title: {{title}}"]
          required: false
          multiple: true
        - name: post
          label: Related Post
          widget: relation
          collection: post
          searchFields: [title]
          valueField: "{{slug}}"
          displayFields: ["url: /{{url}}  - Title: {{title}}"]
          required: false
          multiple: true
```

```njk
{% for page in relatedpages %}
  <div class="flex">

  {# Grap the data from collections. all  #}
  {% for item in collections.all | getPage("/" + page + "/") -%}

    <article class="">
      <a href="{{ item.url }}">
        <h2 class="text-3xl">{{ item.data.title }}</h2>
        <div>{{ item.data.teaser }}</div>

        {# Generate image #}
        {% if item.data.image  %}
          {% set css = "shadow" %}
          {% set srcset = [200] %}
          {% set sizes = "(min-width: 1600px) 50vw, 100vw" %}
          {% set loading = "lazy" %}
          <div class="aspect-square overflow-hidden">
            {% image item.data.image , srcset, sizes, format, alt,css, loading %}
          </div>
        {% endif %}
        {# / Generate image #}
      </a>
      </article>
  {% endfor %}

  </div>

{% endfor %}
```
