### ISSUE TITLE
Files 

### ISSUE THREAD

**Issue by mortendk** [mortendk/saga11#73]
Missing that a user can add files to the website 
Can netlifycms handle files ?

netlifycms
``` yml
- label: "Manual PDF"
  name: "manual_pdf"
  widget: "file"
  default: "/uploads/general-manual.pdf"
  media_library:
    config:
      multiple: true
```
